window.AS_OF = "2026-10-04";

window.MASTERS = {
  inventory: [
    { itemId: 4303, item: "WidgetA", stock: 15 },
    { itemId: 1096, item: "WidgetB", stock: 10 },
    { itemId: 1607, item: "GadgetX", stock: 5 },
    { itemId: 7484, item: "FakeItem", stock: 0 },
  ],
  pricing: [
    { itemId: 4303, item: "WidgetA", unitPrice: 250, updated: "2026-10-04" },
    { itemId: 1096, item: "WidgetB", unitPrice: 500, updated: "2026-10-04" },
    { itemId: 1607, item: "GadgetX", unitPrice: 750, updated: "2026-10-04" },
  ],
  vendors: [
    { vendorId: 5001, name: "Widgets Inc.", address: "100 Main St, Chicago, IL 60601", contact: "Sarah Chen" },
    { vendorId: 5002, name: "Gadgets Co.", address: "", contact: "Daniel Okonkwo" },
    { vendorId: 5003, name: "Fraudster LLC", address: "", contact: "Jonathan Hale" },
    { vendorId: 5004, name: "Precision Parts Ltd.", address: "742 Evergreen Terrace, Springfield, IL 62704", contact: "Travis Muller" },
    { vendorId: 5005, name: "Global Supply Chain Partners", address: "1600 Pennsylvania Ave, Washington, DC 20500", contact: "Michael Torres" },
    { vendorId: 5006, name: "Acme Industrial Supplies", address: "", contact: "Jennifer Walsh" },
    { vendorId: 5007, name: "MegaWidgets Corp", address: "", contact: "David Park" },
    { vendorId: 5008, name: "NoProd Industries", address: "billing@noproduct.biz", contact: "Amanda Foster" },
    { vendorId: 5009, name: "Consolidated Materials Group", address: "", contact: "Christopher Reid" },
    { vendorId: 5010, name: "Summit Manufacturing Co.", address: "", contact: "Robert Klein" },
    { vendorId: 5011, name: "QuickShip Distributers", address: "Formerly FastShip Ltd.", contact: "Kevin Brooks" },
    { vendorId: 5012, name: "Atlas Industrial Supply", address: "500 Commerce Blvd, Detroit, MI 48201", contact: "Lisa Nguyen" },
    { vendorId: 5013, name: "TechParts International", address: "", contact: "James Patterson" },
    { vendorId: 5014, name: "Reliable Components Inc.", address: "", contact: "Emily Watson" },
  ],
};

function line(description, sku, qty, stock, price, master) {
  return {
    description,
    sku,
    qty,
    stock,
    price,
    master,
    lineTotal: Math.round(qty * price * 100) / 100,
  };
}

window.SEED = [
  {
    id: "INV-1001",
    number: "INV-1001",
    vendor: "Widgets Inc.",
    vendorId: 5001,
    contact: "Sarah Chen",
    invoiceDate: "2026-01-15",
    dueDate: "2026-02-01",
    terms: "Net 15",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 5000,
    tax: 0,
    freight: 0,
    total: 5000,
    mathTies: true,
    status: "paid",
    inboxes: [],
    flag: "",
    reason: "Vendor, items, stock, and prices match. Total is inside the standard band.",
    lines: [line("WidgetA", "WidgetA", 10, 15, 250, 250), line("WidgetB", "WidgetB", 5, 10, 500, 500)],
    controls: [],
    commercial: "Routine replenishment from an established supplier. No commercial concern.",
    unresolved: [],
    trace: [
      ["Extractor", "Read invoice_1001.txt and captured two lines."],
      ["Validator", "Vendor 5001 matched. Both lines are within stock and at the master price."],
      ["Approver", "Commercial review approved. No critical or elevated control fired."],
      ["Payment", "Paid 5000.00 to Widgets Inc."],
    ],
    activity: [{ at: "2026-01-15T18:00:00", actor: "Pipeline", text: "Approved and paid." }],
  },
  {
    id: "INV-1002",
    number: "INV-1002",
    vendor: "Gadgets Co.",
    vendorId: 5002,
    contact: "Daniel Okonkwo",
    invoiceDate: "2026-01-30",
    dueDate: "2026-01-30",
    terms: "Net 30",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 15000,
    tax: 0,
    freight: 0,
    total: 15000,
    mathTies: true,
    status: "rejected",
    inboxes: [],
    flag: "",
    reason: "GadgetX quantity 20 exceeds stock of 5. Total is also above $10,000.",
    lines: [line("GadgetX", "GadgetX", 20, 5, 750, 750)],
    controls: [
      { id: 6, severity: "critical", rule: "Quantity exceeds stock", message: "GadgetX requests 20 against stock 5." },
      { id: 1, severity: "elevated", rule: "High-value invoice", message: "Total $15,000 exceeds the $10,000 elevated threshold." },
    ],
    commercial: "The order is three times on-hand stock. Payment was not justified.",
    unresolved: [],
    trace: [
      ["Extractor", "Read the messy Gadgets Co. text invoice."],
      ["Validator", "Vendor matched. GadgetX stock is 5."],
      ["Approver", "Critical stock control overrode any approval."],
      ["Payment", "Not paid."],
    ],
    activity: [{ at: "2026-01-30T12:00:00", actor: "Pipeline", text: "Rejected. Quantity exceeds stock." }],
  },
  {
    id: "INV-1003",
    number: "INV-1003",
    vendor: "Fraudster LLC",
    vendorId: 5003,
    contact: "Jonathan Hale",
    invoiceDate: "2026-01-20",
    dueDate: "",
    terms: "Immediate",
    currency: "USD",
    po: "",
    bank: "Wire transfer preferred",
    subtotal: 100000,
    tax: 0,
    freight: 0,
    total: 100000,
    mathTies: true,
    status: "rejected",
    inboxes: [],
    flag: "",
    reason: "FakeItem quantity 100 against stock 0, total above $25,000, and the invoice demands an immediate wire.",
    lines: [line("FakeItem", "FakeItem", 100, 0, 1000, null)],
    controls: [
      { id: 6, severity: "critical", rule: "Quantity exceeds stock", message: "FakeItem requests 100 against stock 0." },
      { id: 1, severity: "critical", rule: "High-value invoice", message: "Total $100,000 exceeds the $25,000 critical threshold." },
      { id: 14, severity: "elevated", rule: "Unusual payment method", message: "Invoice asks for an immediate wire." },
      { id: 4, severity: "elevated", rule: "Unit-price variance", message: "FakeItem has no pricing-master row." },
    ],
    commercial: "Urgent wire language on a zero-stock item is not a normal production purchase.",
    unresolved: [],
    trace: [
      ["Extractor", "Captured FakeItem, immediate terms, and wire instruction."],
      ["Validator", "Item is on file with zero stock and no price."],
      ["Approver", "Rejected on stock, amount, and payment method."],
      ["Payment", "Not paid."],
    ],
    activity: [{ at: "2026-01-20T09:00:00", actor: "Pipeline", text: "Rejected before payment." }],
  },
  {
    id: "INV-1004",
    number: "INV-1004",
    vendor: "Precision Parts Ltd.",
    vendorId: 5004,
    contact: "Travis Muller",
    invoiceDate: "2026-01-22",
    dueDate: "2026-02-22",
    terms: "Net 30",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 1750,
    tax: 140,
    freight: 0,
    total: 1890,
    mathTies: true,
    status: "paid",
    inboxes: [],
    flag: "",
    reason: "Small matched order. Tax ties.",
    lines: [line("WidgetA", "WidgetA", 3, 15, 250, 250), line("WidgetB", "WidgetB", 2, 10, 500, 500)],
    controls: [],
    commercial: "Ordinary parts replenishment.",
    unresolved: [],
    trace: [
      ["Extractor", "Read the JSON invoice."],
      ["Validator", "Both lines match stock and price."],
      ["Approver", "Approved."],
      ["Payment", "Paid 1890.00 to Precision Parts Ltd."],
    ],
    activity: [{ at: "2026-01-22T16:00:00", actor: "Pipeline", text: "Approved and paid." }],
  },
  {
    id: "INV-1004-R1",
    number: "INV-1004",
    revision: "R1",
    vendor: "Precision Parts Ltd.",
    vendorId: 5004,
    contact: "Travis Muller",
    invoiceDate: "2026-01-22",
    dueDate: "2026-02-22",
    terms: "Net 30",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 5500,
    tax: 440,
    freight: 0,
    total: 5940,
    mathTies: true,
    status: "paid",
    inboxes: [],
    flag: "Total is above $5,000.",
    reason: "Revision adds GadgetX quantity 5, equal to stock. Prices match. Flag acknowledged.",
    lines: [
      line("WidgetA", "WidgetA", 3, 15, 250, 250),
      line("WidgetB", "WidgetB", 2, 10, 500, 500),
      line("GadgetX", "GadgetX", 5, 5, 750, 750),
    ],
    controls: [{ id: 1, severity: "flag", rule: "High-value invoice", message: "Total $5,940 exceeds the $5,000 flag threshold." }],
    commercial: "The added quantity consumes the remaining GadgetX stock and still matches the master price.",
    unresolved: [],
    trace: [
      ["Extractor", "Read revision R1. Not treated as a duplicate."],
      ["Validator", "GadgetX quantity equals stock of 5."],
      ["Approver", "Approved with the $5,000 flag noted."],
      ["Payment", "Paid 5940.00 to Precision Parts Ltd."],
    ],
    activity: [{ at: "2026-01-22T17:00:00", actor: "Pipeline", text: "Revision R1 approved and paid." }],
  },
  {
    id: "INV-1005",
    number: "INV-1005",
    vendor: "Global Supply Chain Partners",
    vendorId: 5005,
    contact: "Michael Torres",
    invoiceDate: "2026-01-18",
    dueDate: "2026-03-18",
    terms: "Net 60",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 14500,
    tax: 725,
    freight: 0,
    total: 15225,
    mathTies: true,
    status: "rejected",
    inboxes: [],
    flag: "",
    reason: "GadgetX quantity 8 exceeds stock of 5.",
    lines: [
      line("WidgetA", "WidgetA", 14, 15, 250, 250),
      line("GadgetX", "GadgetX", 8, 5, 750, 750),
      line("WidgetB", "WidgetB", 10, 10, 500, 500),
    ],
    controls: [
      { id: 6, severity: "critical", rule: "Quantity exceeds stock", message: "GadgetX requests 8 against stock 5." },
      { id: 1, severity: "elevated", rule: "High-value invoice", message: "Total $15,225 exceeds $10,000." },
    ],
    commercial: "Widget lines fit. The gadget quantity does not.",
    unresolved: [],
    trace: [
      ["Extractor", "Read three lines from JSON."],
      ["Validator", "GadgetX is short."],
      ["Approver", "Rejected on stock."],
      ["Payment", "Not paid."],
    ],
    activity: [{ at: "2026-01-18T11:00:00", actor: "Pipeline", text: "Rejected. Quantity exceeds stock." }],
  },
  {
    id: "INV-1006",
    number: "INV-1006",
    vendor: "Acme Industrial Supplies",
    vendorId: 5006,
    contact: "Jennifer Walsh",
    invoiceDate: "2026-01-25",
    dueDate: "2026-02-10",
    terms: "Net 15",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 2750,
    tax: 0,
    freight: 0,
    total: 2750,
    mathTies: true,
    status: "paid",
    inboxes: [],
    flag: "",
    reason: "Matched CSV invoice under the flag threshold.",
    lines: [line("WidgetA", "WidgetA", 5, 15, 250, 250), line("WidgetB", "WidgetB", 3, 10, 500, 500)],
    controls: [],
    commercial: "Standard replenishment.",
    unresolved: [],
    trace: [
      ["Extractor", "Read the field-value CSV."],
      ["Validator", "Both lines matched."],
      ["Approver", "Approved."],
      ["Payment", "Paid 2750.00 to Acme Industrial Supplies."],
    ],
    activity: [{ at: "2026-01-25T14:00:00", actor: "Pipeline", text: "Approved and paid." }],
  },
  {
    id: "INV-1007",
    number: "INV-1007",
    vendor: "MegaWidgets Corp",
    vendorId: 5007,
    contact: "David Park",
    invoiceDate: "2026-01-28",
    dueDate: "2026-02-28",
    terms: "Net 30",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 14750,
    tax: 885,
    freight: 0,
    total: 15525,
    mathTies: true,
    status: "rejected",
    inboxes: [],
    flag: "",
    reason: "WidgetA quantity 20 exceeds stock 15. WidgetB quantity 15 exceeds stock 10.",
    lines: [
      line("WidgetA", "WidgetA", 20, 15, 250, 250),
      line("WidgetB", "WidgetB", 15, 10, 500, 500),
      line("GadgetX", "GadgetX", 3, 5, 750, 750),
    ],
    controls: [
      { id: 6, severity: "critical", rule: "Quantity exceeds stock", message: "WidgetA requests 20 against stock 15. WidgetB requests 15 against stock 10." },
      { id: 1, severity: "elevated", rule: "High-value invoice", message: "Total $15,525 exceeds $10,000." },
    ],
    commercial: "GadgetX fits. The widget quantities do not.",
    unresolved: [],
    trace: [
      ["Extractor", "Read the grid CSV."],
      ["Validator", "Two lines exceed stock."],
      ["Approver", "Rejected."],
      ["Payment", "Not paid."],
    ],
    activity: [{ at: "2026-01-28T10:00:00", actor: "Pipeline", text: "Rejected. Quantity exceeds stock." }],
  },
  {
    id: "INV-1008",
    number: "INV-1008",
    vendor: "NoProd Industries",
    vendorId: 5008,
    contact: "Amanda Foster",
    invoiceDate: "2026-01-10",
    dueDate: "2026-01-20",
    terms: "Net 10",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 9900,
    tax: 0,
    freight: 0,
    total: 9900,
    mathTies: true,
    status: "rejected",
    inboxes: [],
    flag: "",
    reason: "SuperGizmo and MegaSprocket are not in inventory.",
    lines: [line("SuperGizmo", "", 12, null, 400, null), line("MegaSprocket", "", 6, null, 850, null)],
    controls: [{ id: 7, severity: "critical", rule: "Item not found", message: "No inventory match for SuperGizmo or MegaSprocket." }],
    commercial: "The supplier is on file. The materials are not.",
    unresolved: [],
    trace: [
      ["Extractor", "Read the email-style invoice."],
      ["Validator", "Neither item is in the catalog."],
      ["Approver", "Rejected."],
      ["Payment", "Not paid."],
    ],
    activity: [{ at: "2026-01-10T08:30:00", actor: "Pipeline", text: "Rejected. Unknown items." }],
  },
  {
    id: "INV-1009",
    number: "INV-1009",
    vendor: "",
    vendorId: null,
    contact: "",
    invoiceDate: "2026-01-15",
    dueDate: "",
    terms: "",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 1000,
    tax: 0,
    freight: 0,
    total: -250,
    mathTies: false,
    status: "review",
    inboxes: ["vp"],
    flag: "",
    reason: "Vendor was not captured, a quantity is negative, and the printed subtotal does not match the lines.",
    lines: [line("WidgetA", "WidgetA", -5, 15, 250, 250), line("WidgetB", "WidgetB", 2, 10, 500, 500)],
    controls: [
      { id: 0, severity: "critical", rule: "Data integrity", message: "WidgetA quantity is -5 and the total is -250." },
      { id: 2, severity: "critical", rule: "Unknown vendor", message: "Vendor name was not captured." },
      { id: 0, severity: "elevated", rule: "Data integrity", message: "Subtotal 1000.00 does not equal the sum of lines -250.00." },
    ],
    commercial: "This may be a credit memo or a failed extraction. A person needs to decide before any posting.",
    unresolved: ["Is this a credit memo or a bad extraction?"],
    trace: [
      ["Extractor", "Vendor name was empty after a retry."],
      ["Human review", "Held. Required vendor field is missing."],
    ],
    activity: [{ at: "2026-01-15T13:00:00", actor: "Pipeline", text: "Held for the VP inbox. Vendor is missing." }],
  },
  {
    id: "INV-1010",
    number: "INV-1010",
    vendor: "Consolidated Materials Group",
    vendorId: 5009,
    contact: "Christopher Reid",
    invoiceDate: "2026-01-27",
    dueDate: "2026-02-26",
    terms: "Net 30",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 6700,
    tax: 335,
    freight: 150,
    total: 7185,
    mathTies: true,
    status: "review",
    inboxes: ["vp", "cfo"],
    flag: "",
    reason: "A rush WidgetA line is priced at 300 against a master of 250. Extended variance is $200.",
    lines: [
      line("WidgetA", "WidgetA", 8, 15, 250, 250),
      line("WidgetB", "WidgetB", 4, 10, 500, 500),
      line("GadgetX", "GadgetX", 2, 5, 750, 750),
      line("WidgetA (rush order)", "WidgetA", 4, 15, 300, 250),
    ],
    controls: [
      { id: 4, severity: "elevated", rule: "Unit-price variance", message: "Rush WidgetA is 20% above the master price of $250." },
      { id: 21, severity: "elevated", rule: "Rush or expedite", message: "Rush language plus a price gap." },
      { id: 1, severity: "flag", rule: "High-value invoice", message: "Total $7,185 exceeds the $5,000 flag threshold." },
    ],
    commercial: "The rush premium needs a business reason before payment. Cash impact of the premium is $200.",
    unresolved: ["Was the rush caused by a supplier miss, a planning miss, or a customer deadline?"],
    trace: [
      ["Extractor", "Normalized the rush line back to WidgetA."],
      ["Validator", "Stock is sufficient. One price is 20% high."],
      ["Approver", "Held for VP review, with a copy to the CFO."],
    ],
    activity: [{ at: "2026-01-27T15:30:00", actor: "Pipeline", text: "Held in the VP inbox and the CFO inbox." }],
  },
  {
    id: "INV-1011",
    number: "INV-1011",
    vendor: "Summit Manufacturing Co.",
    vendorId: 5010,
    contact: "Robert Klein",
    invoiceDate: "2026-01-20",
    dueDate: "2026-02-20",
    terms: "Net 30",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 3000,
    tax: 0,
    freight: 0,
    total: 3000,
    mathTies: true,
    status: "paid",
    inboxes: [],
    flag: "",
    reason: "Clean matched invoice.",
    lines: [line("WidgetA", "WidgetA", 6, 15, 250, 250), line("WidgetB", "WidgetB", 3, 10, 500, 500)],
    controls: [],
    commercial: "No extra scrutiny required.",
    unresolved: [],
    trace: [
      ["Extractor", "Read the clean text invoice."],
      ["Validator", "Both lines matched."],
      ["Approver", "Approved."],
      ["Payment", "Paid 3000.00 to Summit Manufacturing Co."],
    ],
    activity: [{ at: "2026-01-20T16:00:00", actor: "Pipeline", text: "Approved and paid." }],
  },
  {
    id: "INV-1012",
    number: "INV-1012",
    vendor: "QuickShip Distributers",
    vendorId: 5011,
    contact: "Kevin Brooks",
    invoiceDate: "2026-01-26",
    dueDate: "2026-02-25",
    terms: "Net 30",
    currency: "USD",
    po: "PO-20260115",
    bank: "",
    subtotal: 9500,
    tax: 475,
    freight: 0,
    total: 9975,
    mathTies: true,
    status: "paid",
    inboxes: [],
    flag: "Total is above $5,000.",
    reason: "Names were normalized to master items. Quantities fit and prices match.",
    lines: [
      line("Widget A", "WidgetA", 12, 15, 250, 250),
      line("WidgetB", "WidgetB", 7, 10, 500, 500),
      line("Gadget X", "GadgetX", 4, 5, 750, 750),
    ],
    controls: [{ id: 1, severity: "flag", rule: "High-value invoice", message: "Total $9,975 exceeds the $5,000 flag threshold." }],
    commercial: "Established shipper. The OCR spacing on item names was normalized.",
    unresolved: [],
    trace: [
      ["Extractor", "Normalized Widget A and Gadget X to the catalog names."],
      ["Validator", "Quantities are within stock. Prices match."],
      ["Approver", "Approved with the $5,000 flag noted."],
      ["Payment", "Paid 9975.00 to QuickShip Distributers."],
    ],
    activity: [{ at: "2026-01-26T11:20:00", actor: "Pipeline", text: "Approved and paid." }],
  },
  {
    id: "INV-1013",
    number: "INV-1013",
    vendor: "Atlas Industrial Supply",
    vendorId: 5012,
    contact: "Lisa Nguyen",
    invoiceDate: "2026-01-24",
    dueDate: "2026-03-24",
    terms: "Net 60",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 21040,
    tax: 1472.8,
    freight: 0,
    total: 22562.8,
    mathTies: false,
    status: "rejected",
    inboxes: [],
    flag: "",
    reason: "Summed quantities exceed stock, and the printed total is $50 above subtotal plus tax.",
    lines: [
      line("WidgetA", "WidgetA", 15, 15, 250, 250),
      line("WidgetB", "WidgetB", 10, 10, 500, 500),
      line("GadgetX", "GadgetX", 5, 5, 750, 750),
      line("WidgetA", "WidgetA", 5, 15, 240, 250),
      line("WidgetB", "WidgetB", 8, 10, 480, 500),
      line("GadgetX", "GadgetX", 3, 5, 750, 750),
      line("WidgetA", "WidgetA", 2, 15, 250, 250),
      line("GadgetX", "GadgetX", 1, 5, 750, 750),
    ],
    controls: [
      { id: 6, severity: "critical", rule: "Quantity exceeds stock", message: "WidgetA 22 vs stock 15. WidgetB 18 vs stock 10. GadgetX 9 vs stock 5." },
      { id: 0, severity: "elevated", rule: "Data integrity", message: "Total 22562.80 is $50.00 above subtotal plus tax (22512.80)." },
      { id: 1, severity: "elevated", rule: "High-value invoice", message: "Total exceeds $10,000." },
    ],
    commercial: "Volume discounts are small. The quantity and the $50 tie-out break are not.",
    unresolved: [],
    trace: [
      ["Extractor", "Read eight lines. Header math does not tie."],
      ["Validator", "Summed quantities exceed stock for every item."],
      ["Approver", "Rejected on stock."],
      ["Payment", "Not paid."],
    ],
    activity: [{ at: "2026-01-24T18:00:00", actor: "Pipeline", text: "Rejected. Quantity exceeds stock." }],
  },
  {
    id: "INV-1014",
    number: "INV-1014",
    vendor: "TechParts International",
    vendorId: 5013,
    contact: "James Patterson",
    invoiceDate: "2026-01-26",
    dueDate: "2026-02-26",
    terms: "Net 30",
    currency: "EUR",
    po: "",
    bank: "",
    subtotal: 3750,
    tax: 375,
    freight: 0,
    total: 4125,
    mathTies: true,
    status: "review",
    inboxes: ["cfo", "vp"],
    flag: "",
    reason: "Currency is EUR. WidgetA at 225 is 10% below the USD master of 250. The gap may be FX rather than a discount.",
    lines: [line("WidgetA", "WidgetA", 4, 15, 225, 250), line("WidgetB", "WidgetB", 6, 10, 475, 500)],
    controls: [
      { id: 0, severity: "elevated", rule: "Data integrity", message: "Invoice currency is EUR. The pricing master is USD." },
      { id: 4, severity: "elevated", rule: "Unit-price variance", message: "WidgetA is 10% from the USD master." },
    ],
    commercial: "Do not treat the euro prices as a USD discount until treasury confirms the rate.",
    unresolved: ["Which FX rate should accounts payable use?"],
    trace: [
      ["Extractor", "Read the XML invoice in EUR."],
      ["Validator", "Items match. Prices are not in USD."],
      ["Approver", "Held for the CFO inbox, with a copy to the VP."],
    ],
    activity: [{ at: "2026-01-26T09:40:00", actor: "Pipeline", text: "Held in the CFO inbox and the VP inbox." }],
  },
  {
    id: "INV-1015",
    number: "INV-1015",
    vendor: "Reliable Components Inc.",
    vendorId: 5014,
    contact: "Emily Watson",
    invoiceDate: "2026-01-29",
    dueDate: "2026-02-28",
    terms: "Net 30",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 6500,
    tax: 0,
    freight: 0,
    total: 6500,
    mathTies: true,
    status: "paid",
    inboxes: [],
    flag: "Total is above $5,000.",
    reason: "Prices and quantities match. The $5,000 flag was acknowledged.",
    lines: [
      line("WidgetA", "WidgetA", 10, 15, 250, 250),
      line("WidgetB", "WidgetB", 5, 10, 500, 500),
      line("GadgetX", "GadgetX", 2, 5, 750, 750),
    ],
    controls: [{ id: 1, severity: "flag", rule: "High-value invoice", message: "Total $6,500 exceeds the $5,000 flag threshold." }],
    commercial: "Clean replenishment above the flag line and under $10,000.",
    unresolved: [],
    trace: [
      ["Extractor", "Read the grid CSV."],
      ["Validator", "Three lines matched."],
      ["Approver", "Approved with the flag noted."],
      ["Payment", "Paid 6500.00 to Reliable Components Inc."],
    ],
    activity: [{ at: "2026-01-29T17:10:00", actor: "Pipeline", text: "Approved and paid." }],
  },
  {
    id: "INV-1016",
    number: "INV-1016",
    vendor: "Widgets Inc.",
    vendorId: 5001,
    contact: "Sarah Chen",
    invoiceDate: "2026-01-27",
    dueDate: "2026-02-27",
    terms: "Net 30",
    currency: "USD",
    po: "",
    bank: "",
    subtotal: 3050,
    tax: 183,
    freight: 0,
    total: 3233,
    mathTies: true,
    status: "rejected",
    inboxes: [],
    flag: "",
    reason: "WidgetC is not in inventory or pricing.",
    lines: [
      line("WidgetA", "WidgetA", 4, 15, 250, 250),
      line("WidgetB", "WidgetB", 2, 10, 500, 500),
      line("WidgetC", "", 3, null, 350, null),
    ],
    controls: [{ id: 7, severity: "critical", rule: "Item not found", message: "No inventory match for WidgetC." }],
    commercial: "The supplier is known. WidgetC is not an approved material.",
    unresolved: [],
    trace: [
      ["Extractor", "Read three lines from JSON."],
      ["Validator", "WidgetC is unknown."],
      ["Approver", "Rejected."],
      ["Payment", "Not paid."],
    ],
    activity: [{ at: "2026-01-27T19:00:00", actor: "Pipeline", text: "Rejected. Unknown item." }],
  },
];
